api = "0.11"

[buildpack]
  id = "heroku/chromium"
  version = "1.0.0"
  name = "chromium"

[[stacks]]
id = "*"

[[targets]]
os = "linux"
arch = "arm64"

[[targets]]
os = "linux"
arch = "amd64"

# pack build cnb-chromium-buildpack --buildpack . --builder heroku/builder:24
# pack buildpack package cnb-chromium-buildpack --format file
